### ISSUE TITLE
Add Goerli testnet to endpoints list

### ISSUE THREAD

**Issue by oraclown** [tellor-io/telliot-core#317]
```yaml
- type: RPCEndpoint
  chain_id: 5
  network: goerli
  provider: Infura
  url: wss://goerli.infura.io/ws/v3/{API_KEY}
  explorer: https://goerli.etherscan.io
  ```
